### ISSUE TITLE
task not running

### ISSUE THREAD

**Issue by santiago** [strongloop/grunt-loopback-sdk-angular#18]
i figured `grunt.registerMultiTask` is not callbacking. changing to just `registerTask` does run.

**Comment by bajtos** [comment]
Is this related to some recent changes in grunt? Can you please submit a pull request fixing the problem?

**Comment by bajtos** [comment]
Also: please post a minimal Gruntfile that reproduces the problem, so that I can verify that it's indeed a bug. Run the unit-tests in this repository, they are running Grunt with `registerMultiTask` and they used to pass at the time when they were written.

**Comment by huhao98** [comment]
I've tried in grunt 0.4.2, It always show 'Done, without errors', even without options.

**Comment by bajtos** [comment]
As part of our issue triage process, we are closing items that have been inactive for an extended period of time. Feel free to reopen this issue if you can provide instructions allowing us to reproduce the problem on our machines using the latest version.
