### ISSUE TITLE
Target Specific configuration

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/grunt-loopback-sdk-angular#19]
The docs say that the grunt plugin can be configured like so:

```
grunt.initConfig({
  loopback_sdk_angular: {
    options: {
      // Task-specific options go here.
    },
    your_target: {
      options: {
        // Target-specific options go here.
      }
    },
  },
});
```

But when I try to set it up the `staging` and `production` targets which have slightly different `apiUrl`, don't work, is there a bug or is the configuration incorrect?

```
    loopback_sdk_angular: {
      services: { // default options?
        options: {
          input: './server/server.js',
          output: './client/app/scripts/shoppinpal-loopback.js',
          ngModuleName: 'shoppinpal-loopback',
          apiUrl: 'https://' + grunt.option('subdomain') + '.localtunnel.me' + '<%= buildProperties.restApiRoot %>'
        }
      },
      staging: {
        options: {
          apiUrl: '<%= buildProperties.site.baseUrl %>' + '<%= buildProperties.restApiRoot %>'
        }
      },
      production: {
        options: {
          apiUrl: '<%= buildProperties.site.baseUrl %>' + '<%= buildProperties.restApiRoot %>'
        }
      }
    },
```

I also don't fully understand what the deal with `services` is ... but its what came out of a working example so I stuck with it. According to the docs (http://docs.strongloop.com/display/public/LB/AngularJS+Grunt+plugin#AngularJSGruntplugin-Howtousetheplugin) there is no real reason that default options should be nested under `services` ... is there?

**Comment by bajtos** [comment]
AFAIK, the default options must not be nested at all. See the configuration used by unit-tests in this project's [Gruntfile](https://github.com/strongloop/grunt-loopback-sdk-angular/blob/bfe905e6a0c79e0235891ffd2d611f8969cfc32c/Gruntfile.js#L32-L49).

I believe the following configuration should work correctly:

```js
    loopback_sdk_angular: {
      options: { // default options
        input: './server/server.js',
        output: './client/app/scripts/shoppinpal-loopback.js',
        ngModuleName: 'shoppinpal-loopback',
        apiUrl: 'https://' + grunt.option('subdomain') + '.localtunnel.me' + '<%= buildProperties.restApiRoot %>'
      },
      staging: {
        options: {
          apiUrl: '<%= buildProperties.site.baseUrl %>' + '<%= buildProperties.restApiRoot %>'
        }
      },
      production: {
        options: {
          apiUrl: '<%= buildProperties.site.baseUrl %>' + '<%= buildProperties.restApiRoot %>'
        }
      }
    },

**Comment by crandmck** [comment]
One of the examples in the doc had `services` and the other didn't.  I removed it from http://docs.strongloop.com/display/LB/AngularJS+Grunt+plugin#AngularJSGruntplugin-Example.  
@bajtos PTAL and see if that looks right.

**Comment by pulkitsinghal** [comment]
@crandmck - thanks! In the gitter chat room @doublemarked made a great point about using `LoopBackResourceProvider.setUrlBase(baseUrl + loopbackApiRoot);` to set the `apiUrl` programmatically so that's the approach I'm now taking. Perhaps its worth it for you to document~ize that?

**Comment by pulkitsinghal** [comment]
To summarize:

1. I removed the `apiUrl` from my `Gruntfile` completely:

  ```
    /* jshint ignore:start */
    loopback_sdk_angular: {
      options: {
        input: './server/server.js',
        output: './client/app/scripts/shoppinpal-loopback.js',
        ngModuleName: 'shoppinpal-loopback'
      }
    },
    /* jshint ignore:end */
  ```
2. My angular app initialization changed to have 3 extra arguments (2 of which were specific to how I go about sharing my constants within my app):

  ```
  .config([
    ...', 'LoopBackResourceProvider', 'baseUrl', 'loopbackApiRoot',
    function (..., LoopBackResourceProvider, baseUrl, loopbackApiRoot) {
      ...
      // Configure backend URL
      LoopBackResourceProvider.setUrlBase(baseUrl + loopbackApiRoot);
    }
  ])
  ```

**Comment by pulkitsinghal** [comment]
@bajtos - without the services, only having this doesn't work at all ... loopback_sdk_angular never gets kicked off

**Comment by bajtos** [comment]
The `options` provides default values shared by multiple named sections. Since you don't have any other named section, your grunt configuration is indeed a no-op. You need to rename "option" to something else, e.g. "services".

```js
  /* jshint ignore:start */
  loopback_sdk_angular: {
    services: {
      input: './server/server.js',
      output: './client/app/scripts/shoppinpal-loopback.js',
      ngModuleName: 'shoppinpal-loopback'
    }
  },
  /* jshint ignore:end */
```

@crandmck I have fixed the code in [Grunt Example](http://docs.strongloop.com/display/LB/AngularJS+Grunt+plugin#AngularJSGruntplugin-Example).

**Comment by bajtos** [comment]
See Grunt docs for more information about how the configuration works: http://gruntjs.com/configuring-tasks

**Comment by faustomorales** [comment]
The code above did not work for me. I had to put the options parameter inside services. I know this is closed but just in case someone else stumbles upon this. Here's how mine looks ...
```javascript
loopback_sdk_angular: {
    services: {
        options: {
            input: './server/server.js',
            output: './client/js/lb-services.js'
        }
    }
}
```

**Comment by crandmck** [comment]
Thanks @faustomorales.  Based on what the Grunt docs say, I changed the [doc example](http://docs.strongloop.com/display/LB/AngularJS+Grunt+plugin#AngularJSGruntplugin-Example) as above.
