### ISSUE TITLE
The task isn't generate the lb-services.js file

### ISSUE THREAD

**Issue by rkmax** [strongloop/grunt-loopback-sdk-angular#20]
I'm using the following Gruntfile.js

```js
grunt.loadNpmTasks('grunt-loopback-sdk-angular');
...
grunt.initConfig({
    loopback_sdk_angular: {
      options: {
        input: 'server/server.js',
        output: '<%= yeoman.app %>/scripts/services/lb-services.js'
      }
    },
    ...
```

The output folder exists but the `lb-services.js` file is never generated.

I've tested with

    $ grunt loopback_sdk_angular

    $ grunt build

My build task has

```js
grunt.task.run([
      'clean:server',
      'loopback_sdk_angular',
      'build-config',
      'wiredep',
      'concurrent:server',
      'autoprefixer',
      'run:development',
      'watch'
    ]);
```

I tested the command `lb-ng` and works fine, maybe I'm missing something

**Comment by bajtos** [comment]
You need to add at least one target to loopback_sdk_angular task.

```js
grunt.initConfig({
    loopback_sdk_angular: {
      default: {
        options: {
          input: 'server/server.js',
          output: '<%= yeoman.app %>/scripts/services/lb-services.js'
        },
      }
    },
```

See [our docs](https://docs.strongloop.com/display/LB/AngularJS+Grunt+plugin) and [grunt docs](http://gruntjs.com/configuring-tasks#task-configuration-and-targets) for more details.
