### ISSUE TITLE
Don't run boot scripts

### ISSUE THREAD

**Issue by josx** [strongloop/grunt-loopback-sdk-angular#21]
Right now every time running this task loopback app is initialized with server.js with boot script.
But I am populating my DB on boot scripts and duplicate my data.

Is there any way to solve this? with this task?
or maybe someone can give a clue to change my booting scripts?

**Comment by bajtos** [comment]
This is tricky. Consider the scenario where a boot script adds new models to the app. If we did not run boot scripts, then the code generator would not see all models.

How about the following solution?

1) When running the code generator, set a flag in an environment variable e.g. `ENV=codegen`
2) In your boot script, check the value of this variable and don't populate the DB when running code generator:

```js
module.exports = function(app) {
  if (process.env.ENV === 'codegen') return;
  // now we can import data
}
```

**Comment by josx** [comment]
@bajtos thanks for replying.
I can use your proposed solution. 
As younote thats implies using an env var when running sdk.

**Comment by Morriz** [comment]
This is really not a preferred solution when creating batch jobs. It should be possible in the options hash to disable boot scripts. Could an extra flag to make this configurable be possible in the next release?

Btw, it is bad design to add model behaviour via boot scripts, and should be discouraged.

**Comment by acrodrig** [comment]
@Morriz as I am reading some time after you wrote this, where would you propose to add model behavior? I am trying to implement something like this:

https://docs.strongloop.com/display/public/LB/Creating+a+default+admin+user

Where I add an admin user at boot. Which is the best place to put something like this?

Thanks.

**Comment by baerrach** [comment]
Is the suggestion [Stackoverflow: How to access loopback models without instantiating the server/app](http://stackoverflow.com/a/33807961/552958) good enough?

Move the checking code from inside the boot() callback to outside
```
// start the server if `$ node server.js`
if (require.main === module) {
  boot(app, __dirname, (err) => {
...
```

**Comment by bajtos** [comment]
The original problem - how to skip a boot script populating the database - can be addressed by the solution described in https://github.com/strongloop/grunt-loopback-sdk-angular/issues/21#issuecomment-134564022. I am going to close this issue as resolved.

@Morriz feel free to open a new issue describing in more details how do you envision the new flag to work.
