### ISSUE TITLE
Update loopback-sdk-angular depedency

### ISSUE THREAD

**Issue by erikverheij** [strongloop/grunt-loopback-sdk-angular#24]
Hi there! Could you please update the version of loopback-sdk-angular?

Thanks in advance!

**Comment by davidcheung** [comment]
Looks like issue is nolonger applicable, the current listed sdk is [`^1.10.0`](https://github.com/strongloop/grunt-loopback-sdk-angular/blob/5d65107dc93009b53875c05302e3f1350ba5c054/package.json#L26) which would pickup the latest [`1.10.1`](https://github.com/strongloop/loopback-sdk-angular/blob/57b7a486af1e72736b117764456f32116e812fd5/package.json#L3) 

closing issue now
