### ISSUE TITLE
why loopback app can not be found

### ISSUE THREAD

**Issue by bgdsh** [strongloop/grunt-loopback-sdk-angular#27]
```
Running "loopback_sdk_angular:services" (loopback_sdk_angular) task
Warning: Cannot load LoopBack app server/server.js Use --force to continue.

Aborted due to warnings.
```

Is there anyone can help me ?

**Comment by davidcheung** [comment]
@bgdsh are u still having this issue? sounds like it could be possible misconfiguration

**Comment by Ktl-XV** [comment]
I found out this happens when I add a datasource based on `loopback-component-storage`. At least with `provider: 'filesystem'` and `root: './storage'`

**Comment by Ktl-XV** [comment]
I think this is an upstream issue, opened strongloop/loopback-sdk-angular#255

**Comment by bosco-li** [comment]
Closing since a new issue is open.  Thanks @Ktl-XV for opening a new issue.
